### ISSUE TITLE
luya\crawler\models\Index preview error

### ISSUE THREAD

**Issue by liberosoft** [luyadev/luya-module-crawler#12]
https://github.com/luyadev/luya-module-crawler/blob/3259d1d5d051c7d7a669b53d858435a5d6d938ac/src/models/Index.php#L398

This line will couse a "preg_match_all(): Compilation failed: nothing to repeat at offset 0" error if a $word variable would have empty space at the end. Explode will make an empty string.

Example:
$x = new \luya\crawler\models\Index();
$x->content = 'Test test test';
echo $x->preview('Test ');

**Comment by nadar** [comment]
Thanks, will test and patch release asap.

**Comment by nadar** [comment]
A patch version has been released, thanks for the report.
