### ISSUE TITLE
Error when search term is followed by white space

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-crawler#13]
When e search term is followed by white-space as in "test " (https://www.xyz.ch/suchen?query=test+), this causes and error on line 245 of `luya-core/helpers/StringHelper.php`:

> preg_match_all(): Compilation failed: nothing to repeat at offset 0

**Comment by nadar** [comment]
already fixed in latest release? see https://github.com/luyadev/luya-module-crawler/issues/12
