### ISSUE TITLE
<!-- [CRAWL_IGNORE]--> behaviour

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-crawler#16]
Does the `<!-- [CRAWL_IGNORE]-->` also prevents the crawler from following links or just from indexing the given content? It's not clear from the readme.

I think it should still follow the links and don't index the content, that's the most obvious behaviour for a crawler, isn't it? To prevent the crawler from following links, something like `<!-- [CRAWL_NOFOLLOW] -->` could be used – but I can't think of any use case for that.

**Comment by nadar** [comment]
@TheMaaarc i just did a very quick check, but i have to do a unit test. The links on a page should be added to crawl index whether you use CRAWL_IGNORE and/or CRAWL_FULL_IGNORE.

**Comment by nadar** [comment]
Thanks @luya-bot

**Comment by TheMaaarc** [comment]
@luya-bot 🖕
