### ISSUE TITLE
cannot crawl to submenu level >2

### ISSUE THREAD

**Issue by mysoundmagic** [luyadev/luya-module-crawler#47]
Hi. Crawlers are now able to find and save titles/pages at the top-level (level 1) and 1 level below (level 2). but crawlers don't work on page/content/title at level 3 and so on. check my screenshot.

and also page on level 3 is not displayed

### What is the expected result?
crawler should get all page/content/title in any level

### What do you get instead? (A Screenshot can help us a lot!)
The admin Page
![1](https://user-images.githubusercontent.com/5405947/168439829-5addb4e6-d141-49f0-98f8-8a4500774c9c.png)

The search page. after I run` ./vendor/bin/luya crawler/crawl`
![2](https://user-images.githubusercontent.com/5405947/168439933-d79116a2-1905-48c9-b5d3-5d1373a51f89.png)

page on level 3 is not displayed sorry for posting in here
![3](https://user-images.githubusercontent.com/5405947/168439986-a08b3070-18b4-446b-ae44-b5c75e1c12d9.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

> 1: [in_array('mod_rewrite', apache_get_modules())] true
> 2: [ini_get('short_open_tag')] ''
> 3: [ini_get('error_reporting')] '22527'
> 4: [phpversion()] '7.4.3'
> 5: [php_ini_loaded_file()] '/etc/php/7.4/apache2/php.ini'
> 6: [php_sapi_name()] 'apache2handler'
> 7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.41 (Ubuntu)'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  ^4.0
| PHP Version      | 7.4.3
| Platform         | Apache2, mysql.
| Operating system | linux ubuntu.

**Comment by nadar** [comment]
Hi @mysoundmagic the crawler only crawls what is available on the website. Like a google bot would do. Is menu 3 available in the navigation?

**Comment by mysoundmagic** [comment]
no, menu 3 is not visible, but I could open menu 3 directly using URL.

**Comment by nadar** [comment]
The crawler will only crawl what is available to the web. So you maybe create a sitemap site which contains all url'd

**Comment by nadar** [comment]
You can use events to let the crawler know if there is more (which is not visible to the web https://github.com/luyadev/luya-module-crawler/pull/48/files
