### ISSUE TITLE
cut UTF-8 string problem

### ISSUE THREAD

**Issue by dven84** [luyadev/luya-module-crawler#8]
### What steps will reproduce the problem?
Cyrillic string in query

### What is the expected result?

![image](https://user-images.githubusercontent.com/10542161/43182884-931d5484-8ffc-11e8-8330-41f687e2fd54.png)

### What do you get instead? 
![image](https://user-images.githubusercontent.com/10542161/43182621-7cf46216-8ffb-11e8-97dd-0772097db473.png)

**Comment by nadar** [comment]
Have you used utf8_mb4 charset in your database - as well as in your html document/type?

**Comment by nadar** [comment]
Just saw, you where talking about "query". So what does the query string look like? Or how to reproduce?

**Comment by dven84** [comment]
- utf8_general_ci in DB
- `<meta charset="UTF-8"/>`  in html

The problem is not in the query, but in the result of the search.

For example, index this text:

> Не следует, однако, забывать, что высокое качество позиционных исследований выявляет срочную потребность анализа существующих паттернов поведения. Высокий уровень вовлечения представителей целевой аудитории является четким доказательством простого факта: экономическая повестка сегодняшнего дня в значительной степени обусловливает важность первоочередных требований. Равным образом, реализация намеченных плановых заданий обеспечивает актуальность системы массового участия. Следует отметить, что выбранный нами инновационный путь влечет за собой процесс внедрения и модернизации первоочередных требований. Сложно сказать, почему сделанные на базе интернет-аналитики выводы призваны к ответу. Но дальнейшее развитие различных форм деятельности создает необходимость включения в производственный план целого ряда внеочередных мероприятий с учетом комплекса как самодостаточных, так и внешне зависимых концептуальных решений. Как уже неоднократно упомянуто, акционеры крупнейших компаний, которые представляют собой яркий пример континентально-европейского типа политической культуры, будут преданы социально-демократической анафеме. Ясность нашей позиции очевидна: перспективное планирование, в своем классическом представлении, допускает внедрение поставленных обществом задач. Учитывая ключевые сценарии поведения, существующая теория однозначно определяет каждого участника как способного принимать собственные решения касаемо кластеризации усилий. Имеется спорная точка зрения, гласящая примерно следующее: базовые сценарии поведения пользователей, превозмогая сложившуюся непростую экономическую ситуацию, смешаны с неуникальными данными до степени совершенной неузнаваемости, из-за чего возрастает их статус бесполезности. Приятно, граждане, наблюдать, как базовые сценарии поведения пользователей будут призваны к ответу.

and search "базе интернет-аналитики"

![image](https://user-images.githubusercontent.com/10542161/43186588-8fe2ec32-9008-11e8-8bbe-4b3b5ca14b56.png)

mb_strpos, mb_substr, mb_strlen fix problem in vendor/luyadev/luya-module-crawler/src/models/Index.php

**Comment by nadar** [comment]
it could be a problem here: https://github.com/luyadev/luya-module-crawler/blob/master/src/models/Index.php#L281-L303

**Comment by nadar** [comment]
@dven84 I guess i fixed the problem within those new helpers: https://github.com/luyadev/luya/commit/409071ce8e94bef36685699df789f06ed4cba020

i will replace the current crawler helpers after next core release.
